name: OBSSE
description: To be obsessive person
meta_description: "No obsessive, no successful"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://fernweh6990.github.io'
google_analytics: 'UA-136422308-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://fernweh6990.github.io'
author:         'Hyunsu'
